server:
  port: 8083

spring:
  datasource:
    username: root
    password: 111111
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

#showSql
logging:
  level:
    com:
      example:
        mapper : debug